[package]
name = "aoc21day8"
version = "0.1.0"
authors = ["Jim Smith <agentjsmith@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"itertools" = "0.10.1"